const cards = [
  {
    id: 1,
    name: "T-SHIRT WITH TAPE DETAILS",
    rating: 4.5,
    price: 120,
    sale: null,
    img: "./images/png/t-shirt.png",
  },
  {
    id: 2,
    name: "SKINNY FIT JEANS",
    rating: 3.5,
    price: 240,
    sale: 260,
    img: "./images/png/trousers.png",
  },
  {
    id: 3,
    name: "CHECKERED SHIRT",
    rating: 4.5,
    price: 180,
    sale: null,
    img: "./images/png/redShirt.png",
  },
  {
    id: 4,
    name: "SLEEVE STRIPED T-SHIRT",
    rating: 4.5,
    price: 130,
    sale: 160,
    img: "./images/png/topSellingOrange.png",
  },
  {
    id: 5,
    name: "SVERTICAL STRIPED SHIRT",
    rating: 5,
    price: 212,
    sale: 232,
    img: "./images/png/greenShirt.png",
  },
  {
    id: 6,
    name: "COURAGE GRAPHIC T-SHIRT",
    rating: 4.0,
    price: 145,
    sale: null,
    img: "./images/png/topSellingOrange.png",
  },
  {
    id: 7,
    name: "LOOSE FIT BERMUDA SHORTS",
    rating: 3.0,
    price: 80,
    sale: null,
    img: "./images/png/blueSkirt.png",
  },
  {
    id: 8,
    name: "FADED SKINNY JEANS",
    rating: 4.5,
    price: 210,
    sale: null,
    img: "./images/png/blackTrouser.png",
  },
  {
    id: 9,
    name: "Polo with Contrast Trims",
    rating: 4.0,
    price: 212,
    sale: 242,
    img: "./images/png/bluePoloT-shirt.png",
  },
  {
    id: 10,
    name: "Gradient Graphic T-shirt",
    rating: 3.5,
    price: 145,
    sale: null,
    img: "./images/png/gradientT-shit.png",
  },
  {
    id: 11,
    name: "Polo with Tipping Details",
    rating: 4.5,
    price: 180,
    sale: null,
    img: "./images/png/poloPinkT-shirt.png",
  },
  {
    id: 12,
    name: "Black Striped T-shirt",
    rating: 5,
    price: 120,
    sale: 150,
    img: "./images/png/blackStripesT-shirt.png",
  },
];
